/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Exercise;

import java.awt.Color;

/**
 *
 * @author Windows 10
 */

public class exercisetk3 extends javax.swing.JFrame {

    /**
     * Creates new form exercisetk3
     */
    public exercisetk3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnright = new javax.swing.JButton();
        btnleft = new javax.swing.JButton();
        RadioButtonred = new javax.swing.JRadioButton();
        RadioButtonyellow = new javax.swing.JRadioButton();
        RadioButtonblack = new javax.swing.JRadioButton();
        RadioButtonorange = new javax.swing.JRadioButton();
        RadioButtongreen = new javax.swing.JRadioButton();
        Textpanel = new javax.swing.JPanel();
        text = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        btnright.setText("->");
        btnright.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrightActionPerformed(evt);
            }
        });

        btnleft.setText("<-");
        btnleft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnleftActionPerformed(evt);
            }
        });

        RadioButtonred.setText("Red");
        RadioButtonred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonredActionPerformed(evt);
            }
        });

        RadioButtonyellow.setText("Yellow");
        RadioButtonyellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonyellowActionPerformed(evt);
            }
        });

        RadioButtonblack.setText("Black");
        RadioButtonblack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonblackActionPerformed(evt);
            }
        });

        RadioButtonorange.setText("Orange");
        RadioButtonorange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonorangeActionPerformed(evt);
            }
        });

        RadioButtongreen.setText("Green");
        RadioButtongreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtongreenActionPerformed(evt);
            }
        });

        Textpanel.setBackground(new java.awt.Color(204, 204, 204));
        Textpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        text.setFont(new java.awt.Font("Dubai", 1, 30)); // NOI18N
        text.setForeground(new java.awt.Color(255, 255, 255));
        text.setText("Programming is fun");

        javax.swing.GroupLayout TextpanelLayout = new javax.swing.GroupLayout(Textpanel);
        Textpanel.setLayout(TextpanelLayout);
        TextpanelLayout.setHorizontalGroup(
            TextpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TextpanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(text)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TextpanelLayout.setVerticalGroup(
            TextpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TextpanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(text)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnleft, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnright, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RadioButtonred)
                .addGap(28, 28, 28)
                .addComponent(RadioButtonyellow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(RadioButtonblack)
                .addGap(33, 33, 33)
                .addComponent(RadioButtonorange)
                .addGap(26, 26, 26)
                .addComponent(RadioButtongreen)
                .addContainerGap())
            .addComponent(Textpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioButtonred)
                    .addComponent(RadioButtonyellow)
                    .addComponent(RadioButtonblack)
                    .addComponent(RadioButtonorange)
                    .addComponent(RadioButtongreen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(Textpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnright)
                    .addComponent(btnleft))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadioButtonredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonredActionPerformed
        // TODO add your handling code here:
        if(RadioButtonred.isSelected()==true)
        {
            text.setForeground(Color.red);
        }else{
            text.setForeground(Color.white);
        }
    }//GEN-LAST:event_RadioButtonredActionPerformed

    private void RadioButtonyellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonyellowActionPerformed
        // TODO add your handling code here:
        if(RadioButtonyellow.isSelected()==true)
        {
            text.setForeground(Color.yellow);
        }else{
            text.setForeground(Color.white);
        }
    }//GEN-LAST:event_RadioButtonyellowActionPerformed

    private void RadioButtonblackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonblackActionPerformed
        // TODO add your handling code here:
        if(RadioButtonblack.isSelected()==true)
        {
            text.setForeground(Color.black);
        }else{
            text.setForeground(Color.white);
        }
    }//GEN-LAST:event_RadioButtonblackActionPerformed

    private void RadioButtonorangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonorangeActionPerformed
        // TODO add your handling code here:
        if(RadioButtonorange.isSelected()==true)
        {
            text.setForeground(Color.orange);
        }else{
            text.setForeground(Color.white);
        }
    }//GEN-LAST:event_RadioButtonorangeActionPerformed

    private void RadioButtongreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtongreenActionPerformed
        // TODO add your handling code here:
        if(RadioButtongreen.isSelected()==true)
        {
            text.setForeground(Color.green);
        }else{
            text.setForeground(Color.white);
        }
    }//GEN-LAST:event_RadioButtongreenActionPerformed
    private int currentPosition = 0;
    private void moveText(int amount){
        int textwidth = text.getPreferredSize().width;
        int panelwidth = Textpanel.getSize().width;
        
        int newPosition = currentPosition + amount;
        
        if(newPosition >= 0 && newPosition + textwidth <= panelwidth){
            currentPosition = newPosition;
            text.setLocation(currentPosition, text.getLocation().y);
        }
    }
    private void btnleftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnleftActionPerformed
        // TODO add your handling code here:
        moveText(-5);
    }//GEN-LAST:event_btnleftActionPerformed

    private void btnrightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrightActionPerformed
        // TODO add your handling code here:
        moveText(5);
    }//GEN-LAST:event_btnrightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(exercisetk3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(exercisetk3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(exercisetk3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(exercisetk3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new exercisetk3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioButtonblack;
    private javax.swing.JRadioButton RadioButtongreen;
    private javax.swing.JRadioButton RadioButtonorange;
    private javax.swing.JRadioButton RadioButtonred;
    private javax.swing.JRadioButton RadioButtonyellow;
    private javax.swing.JPanel Textpanel;
    private javax.swing.JButton btnleft;
    private javax.swing.JButton btnright;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
}
